import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
    "./hooks/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#ffdad6",
        "on-primary": "#003915",
        "inverse-primary": "#006e2f",
        "inverse-on-surface": "#2a322a",
        "on-surface": "#dce5d9",
        "on-tertiary": "#60130d",
        "secondary-container": "#0566d9",
        tertiary: "#ffb5ab",
        "tertiary-fixed-dim": "#ffb4a9",
        "primary-fixed-dim": "#4ae176",
        "on-secondary-fixed-variant": "#004395",
        "surface-bright": "#333b33",
        "surface-container-lowest": "#091009",
        "surface-variant": "#2f372e",
        "on-secondary-fixed": "#001a42",
        "on-tertiary-container": "#76231b",
        background: "#0e150e",
        secondary: "#adc6ff",
        outline: "#869585",
        primary: "#4be277",
        "tertiary-container": "#ff8b7c",
        "on-primary-fixed-variant": "#005321",
        "on-secondary-container": "#e6ecff",
        "primary-fixed": "#6bff8f",
        "on-primary-container": "#004b1e",
        "on-tertiary-fixed": "#410001",
        "surface-dim": "#0e150e",
        error: "#ffb4ab",
        "on-error": "#690005",
        "on-background": "#dce5d9",
        "inverse-surface": "#dce5d9",
        "secondary-fixed-dim": "#adc6ff",
        "surface-container-low": "#161d16",
        "error-container": "#93000a",
        "primary-container": "#22c55e",
        "surface-tint": "#4ae176",
        "surface-container-high": "#242c24",
        surface: "#0e150e",
        "on-surface-variant": "#bccbb9",
        "surface-container": "#1a221a",
        "tertiary-fixed": "#ffdad5",
        "secondary-fixed": "#d8e2ff",
        "outline-variant": "#3d4a3d",
        "on-secondary": "#002e6a",
        "on-primary-fixed": "#002109",
        "surface-container-highest": "#2f372e",
        "on-tertiary-fixed-variant": "#7f2a21",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
      spacing: {
        gutter: "16px",
        xl: "32px",
        base: "4px",
        md: "16px",
        "sidebar-width": "260px",
        xs: "8px",
        lg: "24px",
        "chat-list-width": "350px",
        sm: "12px",
      },
      fontFamily: {
        inter: ["Inter", "system-ui", "-apple-system", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": [
          "26px",
          { lineHeight: "32px", fontWeight: "700" },
        ],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": [
          "32px",
          {
            lineHeight: "40px",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "label-md": [
          "12px",
          {
            lineHeight: "16px",
            letterSpacing: "0.05em",
            fontWeight: "500",
          },
        ],
        "headline-sm": [
          "18px",
          { lineHeight: "24px", fontWeight: "600" },
        ],
        "headline-md": [
          "24px",
          {
            lineHeight: "32px",
            letterSpacing: "-0.01em",
            fontWeight: "600",
          },
        ],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
